server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API calls vers les services internes du cluster.
    # Ces noms correspondent aux Services Kubernetes (api-users, api-orders, api-products).
    location /api/users {
        rewrite ^/api/users(.*)$ /users$1 break;
        proxy_pass http://api-users:3001;
    }
    location /api/orders {
        rewrite ^/api/orders(.*)$ /orders$1 break;
        proxy_pass http://api-orders:3002;
    }
    location /api/products {
        rewrite ^/api/products(.*)$ /products$1 break;
        proxy_pass http://api-products:3003;
    }

    location /health {
        return 200 'ok';
    }
}
