plugin: amazon.aws.aws_ec2
regions:
  - eu-west-1
filters:
  tag:Role: k3s
  instance-state-name: running
keyed_groups:
  - key: ec2_tags.Role
    prefix: tag
compose:
  ansible_host: public_ip_address